language: c
sudo: required
env:
  global:
  - OPAMVERBOSE=1
  - OPAMYES=true
  - OPAMKEEPBUILDDIR=true
  - OPAMWITHTEST=true
  matrix:
  - OCAML_VERSION=4.07 COQ_VERSION="8.8.2"
  - OCAML_VERSION=4.07 COQ_VERSION="8.9.0"
os:
  - linux
    # - osx
matrix:
  fast_finish: true
  allow_failures:
  - os: osx
cache:
  apt: true
  directories:
  - $HOME/.opam
  - $HOME/Library/Caches/Homebrew

before_install:
  # Install OCaml and opam
  - curl -L https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh | sh

install:
- eval $(opam config env)
- opam repo add coq-released https://coq.inria.fr/opam/released
- opam repo add coq-extra-dev https://coq.inria.fr/opam/extra-dev
- opam pin add coq $COQ_VERSION
- opam pin add coq-itree --kind=path . -n  # Make opam aware of our dependency constraints
- opam install coq-itree --deps-only -v
- opam list

script:
- set -e
- opam install coq-itree -v
- opam upgrade
- opam remove coq-itree -v
